from tests import IMPLEMENTATION_FOLDER, DEFAULT_RDF_FORMAT, TEST_DATA_FOLDER

TEST_DATA_FOLDER = TEST_DATA_FOLDER / "shacl"
SHAPES_FOLDER = IMPLEMENTATION_FOLDER / "shacl_shapes"
FULL_SHAPES_NAME = "dcat_ap_lu_CM_shapes"
FULL_SHAPES_FORMAT = DEFAULT_RDF_FORMAT
FULL_SHAPES_FILENAME = f"{FULL_SHAPES_NAME}.{FULL_SHAPES_FORMAT}"
FULL_SHAPES_FILE = SHAPES_FOLDER / FULL_SHAPES_FILENAME
