name: Tests

on:
  push:
    branches: [ main , develop , feature/** , release/* ]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update OS
      run: sudo apt-get update
    - name: Install dependencies
      run: make install
    - name: Run Tests
      run: |
        make test
